defaults:
  - _self_  # all below configs will override this conf.yaml
  - robot: r1pro
  - task: behavior
  - policy: ???

env_wrapper: 
  _target_: omnigibson.learning.wrappers.RGBLowResWrapper
policy_name: ???  # filled by policy
headless: true  # whether to run in headless mode (no GUI)
eval_on_train_instances: false  # whether to eval on training instances
eval_instance_ids: null  # specific list of instance ids to eval on, if null test on all instances
write_video: true # whether we record videos during rollout
partial_scene_load: false  # whether to only load task-relevant rooms for a specific task
max_steps: null  # max steps per rollout episode, setting to null will use the default value (2 x average human demo completion steps)
log_path: ???
extra_notes: null
policy_config: pi05_b1k
policy_dir: null
inf_time_proprio_dropout: 0.0  # proportion of time to drop out proprio at inference time
n_ds_steps: 0  # number of steps to use dataset inputs for the policy
use_heavy_robot: false  # whether to use a heavy robot for the policy
use_dataset_inputs: false  # whether to use dataset inputs for the policy
use_dataset_inputs_proprio_only: false  # whether to use dataset inputs for the policy, but only use proprio information
test_hidden: false  # [Internal use only] whether to eval on hidden test instances
prompt: null  # prompt to use for the policy
